const GOAL_TILE = 13
const ROSETTE_TILES = [3, 7, 11]
const PLAYER_START = -1
const MIDLANE_START = 4
const MIDLANE_END = 10
export { GOAL_TILE, ROSETTE_TILES, PLAYER_START, MIDLANE_START, MIDLANE_END }
